# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 202)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(220, 0, 91, 41))
        self.button_add.setObjectName("button_add")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(220, 40, 91, 41))
        self.button_delete.setObjectName("button_delete")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(220, 120, 91, 41))
        self.button_clear.setObjectName("button_clear")
        self.button_calc = QtWidgets.QPushButton(self.centralwidget)
        self.button_calc.setGeometry(QtCore.QRect(220, 160, 91, 40))
        self.button_calc.setObjectName("button_calc")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.button_marja = QtWidgets.QPushButton(self.centralwidget)
        self.button_marja.setGeometry(QtCore.QRect(220, 80, 91, 41))
        self.button_marja.setObjectName("button_marja")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textMarja = QtWidgets.QLineEdit(self.centralwidget)
        self.textMarja.setGeometry(QtCore.QRect(80, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textMarja.setFont(font)
        self.textMarja.setReadOnly(True)
        self.textMarja.setObjectName("textMarja")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BetterCalc"))
        self.button_add.setText(_translate("MainWindow", "Добавить"))
        self.button_delete.setText(_translate("MainWindow", "Удалить"))
        self.button_clear.setText(_translate("MainWindow", "Очистить"))
        self.button_calc.setText(_translate("MainWindow", "Считать"))
        self.button_marja.setText(_translate("MainWindow", "Маржа"))
        self.label.setText(_translate("MainWindow", "Маржа:"))
        self.textMarja.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
